# Thresholds & weights for attention scoring

EAR_OPEN_THRESHOLD = 0.25
EAR_CLOSE_THRESHOLD = 0.15

HEAD_CENTER_THRESHOLD = 10
HEAD_MAX_THRESHOLD = 40

GAZE_WEIGHT = 0.4
HEAD_WEIGHT = 0.3
EYE_WEIGHT = 0.2
FACE_WEIGHT = 0.1
